import destinations from './destinations';
import tours from './tours';
import regions from './regions';
import operators from './operators';
import hotels from './hotels';
import restaurants from './restaurants';
import seasons from './seasons';
import customers from './customers';
import bookings from './bookings';
import reviews from './reviews';
import media from './media';
import bikes from './bikes';
import boats from './boats';
import decks from './decks';
import currencies from './currencies';
import models from './models';
import accommodation_categories from './accommodation_categories';
import room_types from './room_types';
import galleries from './galleries';
import tour_bikes from './tour_bikes';
import tour_routes from './tour_routes';
import tour_extras from './tour_extras';
import tour_reductions from './tour_reductions';
import tour_specifications from './tour_specifications';
import tour_pricing from './tour_pricing';
import tour_seasons from './tour_seasons';
import build from './build';
import global from './global';
import pages from './pages';
import search from './search';
import enquiries from './enquiries';
import newsletter from './newsletter';
import offers from './offers';
import payments from './payments';
import tasks from './tasks';
import notes from './admin_notes';
import auth from './auth';
import express from 'express';
import AuthController from '../controllers/Auth';
import navigations from './navigations';
import homepageCollections from './homepage_collections'
import categories from './categories';

const router = express.Router();

router.use('/regions', regions);
router.use('/destinations', destinations);
router.use('/tours', tours);
router.use('/media', AuthController.is_logged_in(), media);
router.use('/galleries', AuthController.is_logged_in(), galleries);
router.use('/build', build);
router.use('/global', global);
router.use('/pages', pages);
router.use('/search', search);
router.use('/tour-bikes', AuthController.is_logged_in(), tour_bikes);
router.use('/tour-routes', AuthController.is_logged_in(), tour_routes);
router.use('/tour-extras', AuthController.is_logged_in(), tour_extras);
router.use('/tour-reductions', AuthController.is_logged_in(), tour_reductions);
router.use('/tour-specifications', AuthController.is_logged_in(), tour_specifications);
router.use('/tour-pricing', AuthController.is_logged_in(), tour_pricing);
router.use('/tour-seasons', AuthController.is_logged_in(), tour_seasons);
router.use('/operators', AuthController.is_logged_in(), operators);
router.use('/hotels', AuthController.is_logged_in(), hotels);
router.use('/restaurants', AuthController.is_logged_in(), restaurants);
router.use('/seasons', AuthController.is_logged_in(), seasons);
router.use('/reviews', AuthController.is_logged_in(), reviews);
router.use('/customers', AuthController.is_logged_in(), customers);
router.use('/bookings', bookings);
router.use('/bikes', AuthController.is_logged_in(), bikes);
router.use('/boats', AuthController.is_logged_in(), boats);
router.use('/decks', AuthController.is_logged_in(), decks);
router.use('/currencies', AuthController.is_logged_in(), currencies);
router.use('/models', AuthController.is_logged_in(), models);
router.use('/accommodation-categories', AuthController.is_logged_in(), accommodation_categories);
router.use('/room-types', AuthController.is_logged_in(), room_types);
router.use('/notes', AuthController.is_logged_in(), notes);
router.use('/offers', offers);
router.use('/enquiries', enquiries);
router.use('/newsletter', newsletter);
router.use('/payments', payments);
router.use('/tasks', tasks);
router.use('/auth', auth);
router.use('/navigations', navigations);
router.use('/homepage-collections', homepageCollections);
router.use('/categories', categories);
router.get('/', (req, res) => res.json({ message: 'Welcome to the Flexitreks API' }));
router.use('*', (req, res) => res.status(404).json({ error: 'Endpoint does not exist' }));

export default router;
